### ISSUE TITLE
Not working in Automatic1111 version: v1.9.4

### ISSUE THREAD

**Issue by nitinmukesh** [Winfredy/SadTalker#929]
I installed throught Extensions tab and then git checkout dev. On relaunch the SadTalker tab does not appear

![Screenshot 2024-06-18 180221](https://github.com/OpenTalker/SadTalker/assets/2102186/a9752ab4-9cab-446e-ab45-9634e38b6241)

```
C:\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
face_alignment False
Installing requirements for SadTalker
imageio_ffmpeg False
Installing requirements for SadTalker
Applying attention optimization: Doggettx... done.
Model loaded in 7.3s (create model: 1.5s, apply weights to model: 4.7s, apply half(): 0.1s, calculate empty prompt: 0.6s).
librosa False
Installing requirements for SadTalker
yacs False
Installing requirements for SadTalker
av False
Installing requirements for SadTalker
gfpgan False
Installing requirements for SadTalker
"
            SadTalker will not support download all the files from hugging face, which will take a long time.

            please manually set the SADTALKER_CHECKPOINTS in `webui_user.bat`(windows) or `webui_user.sh`(linux)

*** Error executing callback ui_tabs_callback for C:\tut\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py
    Traceback (most recent call last):
      File "C:\tut\stable-diffusion-webui\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\tut\stable-diffusion-webui\extensions\SadTalker\scripts\extension.py", line 172, in on_ui_tabs
        from app_sadtalker import sadtalker_demo
      File "C:\tut\stable-diffusion-webui/extensions/SadTalker\app_sadtalker.py", line 3, in <module>
        from src.gradio_demo import SadTalker
      File "C:\tut\stable-diffusion-webui/extensions/SadTalker\src\gradio_demo.py", line 6, in <module>
        from src.generate_batch import get_data
      File "C:\tut\stable-diffusion-webui/extensions/SadTalker\src\generate_batch.py", line 8, in <module>
        import src.utils.audio as audio
      File "C:\tut\stable-diffusion-webui/extensions/SadTalker\src\utils\audio.py", line 1, in <module>
        import librosa
      File "C:\tut\stable-diffusion-webui\venv\lib\site-packages\librosa\__init__.py", line 211, in <module>
        from . import core
      File "C:\tut\stable-diffusion-webui\venv\lib\site-packages\librosa\core\__init__.py", line 9, in <module>
        from .constantq import *  # pylint: disable=wildcard-import
      File "C:\tut\stable-diffusion-webui\venv\lib\site-packages\librosa\core\constantq.py", line 1058, in <module>
        dtype=np.complex,
      File "C:\tut\stable-diffusion-webui\venv\lib\site-packages\numpy\__init__.py", line 338, in __getattr__
        raise AttributeError(__former_attrs__[attr])
    AttributeError: module 'numpy' has no attribute 'complex'.
    `np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
    The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
        https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 109.7s (prepare environment: 3.7s, import torch: 3.1s, import gradio: 0.7s, setup paths: 2.2s, initialize shared: 1.0s, other imports: 1.4s, load scripts: 2.0s, create ui: 95.5s).

```

![Screenshot 2024-06-18 180309](https://github.com/OpenTalker/SadTalker/assets/2102186/6c21f843-45f3-4331-a85e-de7bf60c084b)

Any clear instructions which help fix the issue as the ones mentioned in Pull request also doesn't work.

**Comment by nitinmukesh** [comment]
```
(venv) C:\tut\stable-diffusion-webui>pip install --upgrade librosa
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: librosa in c:\tut\stable-diffusion-webui\venv\lib\site-packages (0.8.0)
Collecting librosa
  Downloading librosa-0.10.2.post1-py3-none-any.whl (260 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.1/260.1 kB 5.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.1.1 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (4.12.2)
Requirement already satisfied: joblib>=0.14 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (1.4.2)
Requirement already satisfied: lazy-loader>=0.1 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (0.4)
Requirement already satisfied: scipy>=1.2.0 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (1.13.1)
Requirement already satisfied: audioread>=2.1.9 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (3.0.1)
Requirement already satisfied: decorator>=4.3.0 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (5.1.1)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (1.5.0)
Requirement already satisfied: numba>=0.51.0 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (0.60.0)
Requirement already satisfied: pooch>=1.1 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (1.8.2)
Collecting soxr>=0.3.2
  Downloading soxr-0.3.7-cp310-cp310-win_amd64.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.6/184.6 kB ? eta 0:00:00
Requirement already satisfied: soundfile>=0.12.1 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (0.12.1)
Requirement already satisfied: numpy!=1.22.0,!=1.22.1,!=1.22.2,>=1.20.3 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from librosa) (1.26.2)
Collecting msgpack>=1.0
  Downloading msgpack-1.0.8-cp310-cp310-win_amd64.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.1/75.1 kB ? eta 0:00:00
Requirement already satisfied: packaging in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from lazy-loader>=0.1->librosa) (24.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from numba>=0.51.0->librosa) (0.43.0)
Requirement already satisfied: platformdirs>=2.5.0 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from pooch>=1.1->librosa) (4.2.2)
Requirement already satisfied: requests>=2.19.0 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from pooch>=1.1->librosa) (2.32.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn>=0.20.0->librosa) (3.5.0)
Requirement already satisfied: cffi>=1.0 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from soundfile>=0.12.1->librosa) (1.16.0)
Requirement already satisfied: pycparser in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (2.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2024.6.2)
Requirement already satisfied: idna<4,>=2.5 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\tut\stable-diffusion-webui\venv\lib\site-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.3.2)
Installing collected packages: soxr, msgpack, librosa
  Attempting uninstall: librosa
    Found existing installation: librosa 0.8.0
    Uninstalling librosa-0.8.0:
      Successfully uninstalled librosa-0.8.0
Successfully installed librosa-0.10.2.post1 msgpack-1.0.8 soxr-0.3.7

[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) C:\tut\stable-diffusion-webui>pip show librosa
Name: librosa
Version: 0.10.2.post1
Summary: Python module for audio and music processing
Home-page: https://librosa.org
Author: Brian McFee, librosa development team
Author-email: brian.mcfee@nyu.edu
License: ISC
Location: c:\tut\stable-diffusion-webui\venv\lib\site-packages
Requires: audioread, decorator, joblib, lazy-loader, msgpack, numba, numpy, pooch, scikit-learn, scipy, soundfile, soxr, typing-extensions
Required-by:
```
After this SadTalker Tab appears in WebUI.

But this error appears

<img width="1241" alt="image" src="https://github.com/OpenTalker/SadTalker/assets/2102186/b5265fcc-7d01-486a-a769-c0df86a214fc">

**Comment by oisilener1982** [comment]
Sadly there are no devs to help us. The last update was almost a year ago

**Comment by oisilener1982** [comment]
It is actually working in 1.9.4

D:\StableDiffusion\stable-diffusion-webui>git pull
Already up to date.
venv "D:\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.4
Commit hash: feee37d75f1b168768014e4634dcb156ee649c05
ReActor preheating... Device: CUDA
Launching Web UI with arguments: --xformers
ControlNet preprocessor location: D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-06-19 00:18:00,349 - ControlNet - INFO - ControlNet v1.1.449
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 23, in <module>
        from modules.ui import (
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (D:\StableDiffusion\stable-diffusion-webui\modules\ui.py)

---
00:18:02 - ReActor - STATUS - Running v0.6.0-a4
Loading weights [15012c538f] from D:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV60B1_v51VAE.safetensors
Creating model from config: D:\StableDiffusion\stable-diffusion-webui\configs\v1-inference.yaml
2024-06-19 00:18:07,760 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Startup time: 87.2s (initial startup: 0.1s, prepare environment: 27.4s, import torch: 11.6s, import gradio: 5.9s, setup paths: 8.9s, initialize shared: 1.2s, other imports: 4.8s, list SD models: 0.3s, load scripts: 6.3s, initialize extra networks: 1.3s, scripts before_ui_callback: 0.2s, create ui: 18.4s, gradio launch: 1.6s).
using safetensor as default
{'checkpoint': 'D:\\StableDiffusion\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'D:\\StableDiffusion\\stable-diffusion-webui/extensions/SadTalker/src/config', 'audio2pose_yaml_path': 'D:\\StableDiffusion\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'D:\\StableDiffusion\\stable-diffusion-webui/extensions/SadTalker/src/config\\auido2exp.yaml', 'use_safetensor': True, 'mappingnet_checkpoint': 'D:\\StableDiffusion\\stable-diffusion-webui\\extensions\\SadTalker\\checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'D:\\StableDiffusion\\stable-diffusion-webui/extensions/SadTalker/src/config\\facerender.yaml'}
Applying attention optimization: xformers... done.
Model loaded in 65.7s (load weights from disk: 4.2s, create model: 2.5s, apply weights to model: 41.6s, apply half(): 0.3s, move model to device: 1.5s, load textual inversion embeddings: 2.1s, calculate empty prompt: 13.2s).
C:\Users\Renel\AppData\Local\Temp\gradio\tmpkthsdc2y.png
landmark Det:: 100%|█████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.06it/s]
3DMM Extraction In Video:: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.88it/s]
mel:: 100%|████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:00<?, ?it/s]
audio2exp:: 100%|████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 14.22it/s]
Face Renderer:: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:04<00:00,  4.52it/s]
The generated video is named ./results/92f46d1c-a6eb-4d40-9fbf-58a41155e2ac/tmpkthsdc2y##Son-0-100.mp4
The generated video is named tmpkthsdc2y##Son-0-100 in ./results/92f46d1c-a6eb-4d40-9fbf-58a41155e2ac

**Comment by nitinmukesh** [comment]
@oisilener1982 
I guess you are using the basic version of SadTalker.

Please could you enable virtual environment and do pip list.
Please post

**Comment by oisilener1982** [comment]
(venv) C:\Users\Renel\Pictures\StableDiffusion\stable-diffusion-webui>pip list
Package                   Version
------------------------- ------------------
absl-py                   2.1.0
accelerate                0.21.0
addict                    2.4.0
aenum                     3.1.15
aiofiles                  23.2.1
aiohttp                   3.9.3
aiosignal                 1.3.1
albumentations            1.4.3
altair                    5.2.0
antlr4-python3-runtime    4.9.3
anyio                     3.7.1
async-timeout             4.0.3
attrs                     23.2.0
audioread                 3.0.1
av                        12.0.0
basicsr                   1.4.2
blendmodes                2022
certifi                   2024.2.2
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        3.3.2
clean-fid                 0.1.35
click                     8.1.7
clip                      1.0
colorama                  0.4.6
coloredlogs               15.0.1
colorlog                  6.8.2
contourpy                 1.2.0
cssselect2                0.7.0
cycler                    0.12.1
Cython                    3.0.9
decorator                 5.1.1
deprecation               2.1.0
depth_anything            2024.1.22.0
diskcache                 5.6.3
dsine                     2024.3.23
easydict                  1.13
einops                    0.4.1
embreex                   2.17.7.post4
exceptiongroup            1.2.0
face-alignment            1.3.5
facexlib                  0.3.0
fastapi                   0.94.0
ffmpy                     0.3.2
filelock                  3.13.3
filterpy                  1.4.5
flatbuffers               24.3.25
fonttools                 4.50.0
frozenlist                1.4.1
fsspec                    2024.3.1
ftfy                      6.2.0
future                    1.0.0
fvcore                    0.1.5.post20221221
geffnet                   1.0.2
gfpgan                    1.3.8
gitdb                     4.0.11
GitPython                 3.1.32
glob2                     0.5
gradio                    3.41.2
gradio_client             0.5.0
grpcio                    1.62.1
h11                       0.12.0
handrefinerportable       2024.2.12.0
httpcore                  0.15.0
httpx                     0.24.1
huggingface-hub           0.22.1
humanfriendly             10.0
idna                      3.6
imageio                   2.34.0
imageio-ffmpeg            0.4.9
importlib_metadata        7.1.0
importlib_resources       6.4.0
inflection                0.5.1
insightface               0.7.3
iopath                    0.1.9
jax                       0.4.25
Jinja2                    3.1.3
joblib                    1.3.2
jsonmerge                 1.8.0
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
kornia                    0.6.7
lark                      1.1.2
lazy_loader               0.3
librosa                   0.8.0
lightning-utilities       0.11.1
llvmlite                  0.42.0
lmdb                      1.4.1
lxml                      5.1.0
mapbox-earcut             1.0.1
Markdown                  3.6
MarkupSafe                2.1.5
matplotlib                3.8.3
mediapipe                 0.10.11
ml-dtypes                 0.3.2
mpmath                    1.3.0
multidict                 6.0.5
networkx                  3.2.1
numba                     0.59.1
numpy                     1.26.2
omegaconf                 2.2.3
onnx                      1.16.0
onnxruntime               1.17.1
onnxruntime-gpu           1.17.1
open-clip-torch           2.20.0
opencv-contrib-python     4.9.0.80
opencv-python             4.9.0.80
opencv-python-headless    4.9.0.80
opt-einsum                3.3.0
orjson                    3.9.15
packaging                 24.0
pandas                    2.2.1
piexif                    1.1.3
Pillow                    9.5.0
pillow-avif-plugin        1.4.3
pip                       22.2.1
platformdirs              4.2.0
pooch                     1.8.1
portalocker               2.8.2
prettytable               3.10.0
protobuf                  3.20.3
psutil                    5.9.5
pycollada                 0.8
pycparser                 2.21
pydantic                  1.10.14
pydub                     0.25.1
pyparsing                 3.1.2
pyreadline3               3.4.1
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytorch-lightning         1.9.4
pytz                      2024.1
PyWavelets                1.5.0
pywin32                   306
PyYAML                    6.0.1
referencing               0.34.0
regex                     2023.12.25
reportlab                 4.1.0
requests                  2.31.0
resampy                   0.4.3
resize-right              0.0.2
rpds-py                   0.18.0
Rtree                     1.2.0
safetensors               0.4.2
scikit-image              0.21.0
scikit-learn              1.4.1.post1
scipy                     1.12.0
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                69.5.1
shapely                   2.0.3
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
sounddevice               0.4.6
soundfile                 0.12.1
spandrel                  0.1.6
starlette                 0.26.1
svg.path                  6.3
svglib                    1.5.1
sympy                     1.12
tabulate                  0.9.0
tb-nightly                2.17.0a20240329
tensorboard-data-server   0.7.2
termcolor                 2.4.0
threadpoolctl             3.4.0
tifffile                  2024.2.12
timm                      0.9.16
tinycss2                  1.2.1
tokenizers                0.13.3
tomesd                    0.1.3
tomli                     2.0.1
toolz                     0.12.1
torch                     2.1.2+cu121
torchdiffeq               0.2.3
torchmetrics              1.3.2
torchsde                  0.2.6
torchvision               0.16.2+cu121
tqdm                      4.66.2
trampoline                0.1.2
transformers              4.30.2
trimesh                   4.2.2
typing_extensions         4.10.0
tzdata                    2024.1
urllib3                   2.2.1
uvicorn                   0.29.0
vhacdx                    0.0.6
wcwidth                   0.2.13
webencodings              0.5.1
websockets                11.0.3
Werkzeug                  3.0.1
wget                      3.2
xatlas                    0.0.9
xformers                  0.0.23.post1
xxhash                    3.4.1
yacs                      0.1.8
yapf                      0.40.2
yarl                      1.9.4
zipp                      3.18.1
WARNING: There was an error checking the latest version of pip.

(venv) C:\Users\Renel\Pictures\StableDiffusion\stable-diffusion-webui>

**Comment by Zati1980** [comment]
WHat have you done that sadtalker is working for you ? 
I have the same error :)).
 AttributeError: module 'numpy' has no attribute 'complex'.
    `np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
    The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
        https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?
  
Do you know any other options for the talking Heads (SadTalker) I have copy models to the folder, I have put (set) in webui path where the models are. 
Can you help me to run the sadtalker ?

**Comment by newgenai79** [comment]
@oisilener1982 

No luck. I did tried to install all dependencies as per the installed libs provided by you.

AttributeError: module 'numpy' has no attribute 'complex'.
It can be fixed by "pip install --upgrade librosa"

After this there is different issue.

Please if possible zip the **SadTalker** folder inside "stable-diffusion-webui\extensions" and upload it. I want to see if there is different version installed at your end.

**Comment by oisilener1982** [comment]
This project is dead anyway. There are alternatives like V-express, Hallo (use pinokio) and Hedra

And there projects with great demo like Vasa-1 and Emo

**Comment by oisilener1982** [comment]
You can solve the numpy problem by backreading the issues and there are solutions provided by some users.

**Comment by newgenai79** [comment]
> You can solve the numpy problem by backreading the issues and there are solutions provided by some users.

Yes did tried that. I think several are struggling with this in Auto1111.

**Comment by newgenai79** [comment]
> This project is dead anyway. There are alternatives like V-express, Hallo (use pinokio) and Hedra
> 
> And there projects with great demo like Vasa-1 and Emo

I know it is dead, still it produce good results. V-express is okay and Hallo is useless. It is taking 8 hrs for 7 sec audio. So unless it is optimized it's not usable. Vasa-1 is not going to be release for general public from last I know and so is Emo.

Thanks for the inputs you provided.

**Comment by oisilener1982** [comment]
We have different result. My 10gb rtx 3080 can only handle 2 seconds of v-express while it is doing fine in Hallo

Its just sad that this project is dead. I am getting better results from sadtalker in terms of Skin Texture and quality. I posted in V-express and even the devs that use Comfyui cant produce better result than Sadtalker. The main weakness of sadtalker is the Emotion. IF they can only fix this, even just a little emotion and sadtalker would be the best

**Comment by oisilener1982** [comment]
Here is the solution for those who are getting numpy error. Just read from the top to bottom

https://github.com/OpenTalker/SadTalker/issues/822#issuecomment-2053857698

Another way would be to go to sadtalker folder.\StableDiffusion\stable-diffusion-webui\extensions\SadTalker and click the webui.bat. I dont know if this is what is meant as the basic version, as mentioned previously, but I don't use this method. However, this should work just fine.

**Comment by TijuanaKez** [comment]
meh. So annoying even with python environments these days we get these dependancy versions issues. Upgrading librosa fixes the 'complex' issue. But for me I now get.
```
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
